"""
Re-classifies only the tables marked 'uncertain' in a previous
auto_classify_tables.py run — much faster than a full re-run, since it
skips the slow SELECT COUNT(*) step entirely (reuses row counts already
in the CSV) and only makes LLM calls for the tables that need it.

Usage:
    python retry_uncertain.py
    (reads table_classification_review.csv from the previous run)

Output: updates table_classification_review.csv and
table_classification_suggested.py in place — re-classified tables are
merged back in, everything else is left untouched.
"""

import csv

from database.connection import get_hospital_connection
from config import settings
from auto_classify_tables import classify_batch, CATEGORIES, BATCH_SIZE


def get_columns_only(conn, table_names: list) -> dict:
    """Just columns, no row counts — those are already known from the CSV."""
    result = {}
    for table_name in table_names:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS "
            "WHERE TABLE_NAME = ? ORDER BY ORDINAL_POSITION",
            (table_name,)
        )
        result[table_name] = [row[0] for row in cursor.fetchall()]
    return result


def run():
    with open("table_classification_review.csv", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    uncertain = [r for r in rows if r["category"] == "uncertain"]
    if not uncertain:
        print("No 'uncertain' rows found — nothing to retry.")
        return

    print(f"Found {len(uncertain)} uncertain tables to retry.\n")

    conn = get_hospital_connection()
    if not conn:
        print("Could not connect to the database. Check your .env MSSQL_* settings.")
        return

    table_names = [r["table"] for r in uncertain]
    columns_by_table = get_columns_only(conn, table_names)
    conn.close()

    from langchain_groq import ChatGroq
    llm = ChatGroq(model="openai/gpt-oss-20b", temperature=0, api_key=settings.groq_api_key, max_tokens=4000)

    updated = {}
    for i in range(0, len(uncertain), BATCH_SIZE):
        batch_rows = uncertain[i:i + BATCH_SIZE]
        batch = [
            {"table": r["table"], "row_count": r["row_count"], "columns": columns_by_table.get(r["table"], [])}
            for r in batch_rows
        ]
        print(f"Retrying batch {i // BATCH_SIZE + 1} ({len(batch)} tables)...")
        results = classify_batch(llm, batch)
        for r in results:
            if isinstance(r, dict) and r.get("table"):
                updated[r["table"]] = r

    changed = 0
    for row in rows:
        if row["table"] in updated:
            new = updated[row["table"]]
            if new["category"] != "uncertain":
                row["category"] = new["category"]
                row["reasoning"] = new.get("reasoning", "") + " (retry)"
                changed += 1

    rows.sort(key=lambda r: (r["category"], -int(r["row_count"] or 0)))

    with open("table_classification_review.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["table", "row_count", "category", "reasoning"])
        writer.writeheader()
        writer.writerows(rows)

    with open("table_classification_suggested.py", "w", encoding="utf-8") as f:
        f.write('"""\nAuto-generated by auto_classify_tables.py / retry_uncertain.py — REVIEW BEFORE USE.\n"""\n\n')
        f.write("SUGGESTED_TABLE_TO_CATEGORY = {\n")
        for row in rows:
            if row["category"] in CATEGORIES:
                f.write(f'    "{row["table"].lower()}": "{row["category"]}",  # {row["reasoning"]}\n')
        f.write("}\n")

    still_uncertain = sum(1 for r in rows if r["category"] == "uncertain")
    print(f"\nResolved {changed} of {len(uncertain)} previously-uncertain tables.")
    print(f"Still uncertain: {still_uncertain} (genuinely ambiguous — worth a manual look)")
    print("Updated table_classification_review.csv and table_classification_suggested.py")


if __name__ == "__main__":
    run()