"""
Auto-generated by auto_classify_tables.py / retry_uncertain.py — REVIEW BEFORE USE.
"""

SUGGESTED_TABLE_TO_CATEGORY = {
    "mstappbookingno": "admissions",  # booking number definitions
    "mstappbookingslots": "admissions",  # booking slot schedule
    "trninvstatus": "billing",  # invoice status tracking
    "trnmodeofcollectionsdet": "billing",  # collection mode details
    "msttallyregledger": "billing",  # ledger entries
    "trnreferalmanagementdet": "billing",  # referral bill details
    "trnreferalmgmtbilldtls": "billing",  # referral bill details
    "trninvpaydetails": "billing",  # invoice payment details
    "trnreferalmanagementpri": "billing",  # primary referral management
    "trnreferalpayments": "billing",  # referral payments
    "mstrefdoc": "billing",  # reference document for billing
    "trnmergeddocbilldtls_referral": "billing",  # merged doc referral billing
    "trnmergeddocbilldtls": "billing",  # merged document billing
    "trncomppayments": "billing",  # company payments (retry)
    "trninvoicegeneration": "billing",  # invoice creation data
    "trninvoicepayments": "billing",  # payment transaction details
    "trncomppaymodedetails": "billing",  # payment mode details
    "trnpaymodechangelog": "billing",  # payment mode change log
    "trndelcreditbill": "billing",  # deleted credit bill
    "trninvstatusupdatelog": "billing",  # invoice status update log
    "trntrackcreditamts_new": "billing",  # credit amount tracking (retry)
    "mstpaymentdetails": "billing",  # payment transaction records
    "trnreferalmgmtbilldtls_del": "billing",  # deleted referral bill details
    "trnreferalmanagementdet_delete": "billing",  # deleted referral bill details
    "trnreferalpartialpayments": "billing",  # partial payments
    "trnccoutrptremarks": "billing",  # billing remarks (retry)
    "msttempapppaymentdtls": "billing",  # payment details
    "trnreferalmanagementpri_del": "billing",  # deleted primary referral
    "trntempdaycollall": "billing",  # daily collection summary (retry)
    "msttemptallyregledger": "billing",  # ledger entries
    "msttallyledgermaster": "billing",  # ledger master
    "trnreferalpayments_del": "billing",  # deleted referral payments
    "trnrejbillscancellationlog": "billing",  # rejected bill cancellation log
    "trnccpayments": "billing",  # company payments (retry)
    "mstreportstatus": "billing",  # report status tracking
    "trnappinvpri": "billing",  # invoice primary data
    "trninvoicetestlog": "billing",  # invoice test log entries
    "mstmemplansec": "billing",  # secondary membership plan
    "tbltempledgerorg": "billing",  # org ledger totals
    "mstmemplans": "billing",  # membership plans
    "mstmemplanwisebenefits": "billing",  # plan benefits
    "trntempbranchwisecoll": "billing",  # branch collection summary (retry)
    "trncomppaymentsrenova": "billing",  # company payments (retry)
    "mstheaderpaytype": "billing",  # payment type header
    "msttaxcategory": "billing",  # tax categories
    "tblappagenttrack": "billing",  # agent bill tracking
    "trncompwiseconcessions": "billing",  # invoice concessions
    "mstinvoicesliptext": "billing",  # invoice slip text
    "tblappagentassignbill": "billing",  # bill assignment to agent
    "mstconceperson": "billing",  # concession holders
    "mstcoupons": "billing",  # coupon definitions
    "mstappadditionalcharges": "billing",  # additional charge definitions
    "mstconcegiven": "billing",  # concession names for billing
    "mstmemplanpri": "billing",  # membership plan primary
    "mstmemplanswiseadditionalcharges": "billing",  # additional charges
    "tblapprepocharges": "billing",  # repository charge definitions
    "cc_invoice": "billing",  # invoice records
    "cc_invoicenew": "billing",  # invoice records
    "customers": "billing",  # customer list
    "daycollection_mobileapp": "billing",  # daily collection summary
    "mstccinvestigationrates": "billing",  # pricing for investigations
    "mstccreg": "billing",  # client registration with balances
    "mstcouponinvdtls": "billing",  # coupon usage details
    "mstdocdeptinvdiscount": "billing",  # invoice discount
    "mstfiles": "billing",  # billing attachment
    "mstluxarytax": "billing",  # room tax for luxury rooms
    "mstorgdeptdiscount": "billing",  # department discount rates
    "mstrefdocamtmapping": "billing",  # doc amount mapping
    "mstrefdocmapping": "billing",  # doc to subdept mapping
    "msttallyledgertypeinfo": "billing",  # ledger type info
    "msttariffupdations": "billing",  # tariff updates
    "msttariffupdations_storecproc": "billing",  # tariff updates
    "paymentgatewayresponse": "billing",  # payment transaction data
    "tarifftable": "billing",  # tariff rates for services
    "tblccinvdetails": "billing",  # invoice details
    "tblcreditperiodgen": "billing",  # credit period
    "tblinvoicesms": "billing",  # invoice and SMS details
    "tbltempledger": "billing",  # ledger totals
    "trnacntvoupaymntmodeofcolctndetails": "billing",  # payment mode details
    "trnageingreport": "billing",  # accounts receivable ageing
    "trnbillingcycleinvoicegeneration": "billing",  # invoice generation cycle
    "trnbillingcyclerates": "billing",  # billing rates
    "trnbulkcancellog": "billing",  # bulk invoice cancellation
    "trncrbillno": "billing",  # credit bill
    "trncreditsales": "billing",  # credit sales
    "trnpaymntgtacknowledgement": "billing",  # payment acknowledgement record
    "trnreferalcancellation": "billing",  # referral cancellation billing
    "trnreferalpartialpayments_del": "billing",  # deleted partial payments
    "trnvouchergen": "billing",  # voucher generation for payments
    "trncc_clubbedreport": "billing",  # clubbed billing report (retry)
    "trncc_cshcrypayments": "billing",  # payment records (retry)
    "trncc_cshcrypaymodedetails": "billing",  # payment mode details (retry)
    "trnccinvoicegeneration": "billing",  # invoice generation (retry)
    "trnccpayments1": "billing",  # payment summary (retry)
    "trnccpaymodedetails": "billing",  # payment mode info (retry)
    "trnclubbed": "billing",  # clubbed bills (retry)
    "trnclubbedreport": "billing",  # clubbed report (retry)
    "trnecommprinttrack": "billing",  # print tracking (retry)
    "trnexecutivecashpayment": "billing",  # cash payment transaction (retry)
    "trnexecutivedenomination": "billing",  # cash denomination record (retry)
    "trnhvadditionalcharges": "billing",  # additional charges (retry)
    "trntariffupdate": "billing",  # tariff update (retry)
    "trntempmoncoll": "billing",  # billing monetary collection (retry)
    "trntemprejbills": "billing",  # billing rejected bills (retry)
    "trntempshiftcollecrpt": "billing",  # billing shift collection (retry)
    "trntrackcreditamts": "billing",  # billing credit tracking (retry)
    "mstrefdoctor": "doctors",  # doctor master data
    "trnmergeddoctors": "doctors",  # merged doctor records
    "mstreferralgroup": "doctors",  # referral group info
    "mstspecialization": "doctors",  # doctor specialization lookup
    "mstccrefdoctor": "doctors",  # doctor reference
    "mstdoctor": "doctors",  # doctor master
    "mstdoctornew": "doctors",  # doctor master
    "mstdoctorslab": "doctors",  # doctor fee slab
    "mstmapauthdoc": "doctors",  # auth doc mapping
    "mstmapsubauthdoc": "doctors",  # sub auth doc mapping
    "mstrefdocclinicinfo": "doctors",  # clinic info for docs
    "mstrefdoctornew": "doctors",  # doctor master data
    "mstreferalcontacts": "doctors",  # referral contact list
    "mstschedule": "doctors",  # doctor schedule slots
    "msttimings": "doctors",  # doctor schedule
    "tbltimings": "doctors",  # doctor slot timings
    "trndoctorweeklyoffs": "doctors",  # doctor off days (retry)
    "trnrefgroupinvmapping": "inventory",  # group to inventory mapping
    "priceupdatelog": "inventory",  # log of inventory price changes
    "mstinvpackageslog": "inventory",  # log of package rates
    "trngrndetails": "inventory",  # goods received detail (retry)
    "trnpurchaseorderdtls": "inventory",  # purchase order line items
    "priceupdate": "inventory",  # price update for inventory items
    "trnstock": "inventory",  # stock inventory (retry)
    "mstmachineparameters": "inventory",  # machine parameters
    "trnpurchaseorderpendingdtls": "inventory",  # pending purchase order lines
    "trngrntandc": "inventory",  # grn terms conditions (retry)
    "trngrnmaster": "inventory",  # grn master record (retry)
    "mstitems": "inventory",  # master list of items
    "trnpotandc": "inventory",  # purchase order terms & conditions
    "trnpurchaseorder": "inventory",  # purchase order header
    "kompprice": "inventory",  # price list
    "trncompmodificationlog": "inventory",  # inventory modification log (retry)
    "trnitemtrack": "inventory",  # inventory item tracking
    "mstitemsr": "inventory",  # alternate item list
    "trnopeningstock": "inventory",  # opening stock
    "trntempinvdet": "inventory",  # inventory detail (retry)
    "msttempappinvdtls": "inventory",  # temp inventory details
    "attapur-price": "inventory",  # price list
    "konnectstock": "inventory",  # stock levels
    "mstunits": "inventory",  # unit master
    "mstsuppliers": "inventory",  # supplier master
    "mstinvprecautions": "inventory",  # precautions for inventory items
    "bnreddy-price": "inventory",  # price list
    "tblinvtemplates": "inventory",  # inventory templates
    "mstappdiseaseinvdtls": "inventory",  # disease inventory details
    "mstsubitemtype": "inventory",  # item type master
    "mstmachineinvmethodmap": "inventory",  # machine to method mapping
    "mstmachinemethodmap": "inventory",  # maps machines to methods
    "trndeptconsumptiondet": "inventory",  # department consumption
    "trndeptconsumptionpri": "inventory",  # department consumption header
    "mstuom": "inventory",  # UOM master
    "mstitemtype": "inventory",  # item type definitions
    "trngrnreturnsdetails": "inventory",  # grn return detail (retry)
    "trngrnreturns": "inventory",  # grn return master (retry)
    "mstmanufacturers": "inventory",  # manufacturer details
    "mstuommapping": "inventory",  # UOM mapping
    "mstantibiotics": "inventory",  # master list of antibiotics
    "mstoutsourceinvmapping": "inventory",  # outsourced inventory mapping
    "mstitemunit": "inventory",  # unit definitions
    "mstrack": "inventory",  # storage rack info
    "msttray": "inventory",  # inventory tray
    "rackmaster": "inventory",  # rack master for inventory
    "setinventorytypes": "inventory",  # inventory type definitions
    "trnconsignment": "inventory",  # consignment inventory
    "trnconsignmentdtls": "inventory",  # consignment details
    "trnquotation": "inventory",  # quotation header
    "trnquotationdetails": "inventory",  # quotation line items
    "trnquotationtandc": "inventory",  # quotation terms & conditions
    "ecomratevsaipl": "inventory",  # price list
    "leela": "inventory",  # price list
    "mdata": "inventory",  # price list
    "mstconsumptionmaster": "inventory",  # item consumption master
    "mstdis_inv_insert": "inventory",  # inventory insert log
    "mstinvconsumables": "inventory",  # consumable inventory
    "mstinvinventorymap": "inventory",  # inventory mapping
    "mstinvpackages2": "inventory",  # package rates for lab tests
    "mstinvprecautionslog": "inventory",  # log of inventory precautions
    "mstinvscheduledet": "inventory",  # schedule for inventory items
    "mstitemdeptaccess": "inventory",  # department access to items
    "mstitemsubunit": "inventory",  # sub-unit definitions
    "mstitemtraymap": "inventory",  # tray mapping for items
    "mstitemunitmapping": "inventory",  # unit mapping
    "mstmachine": "inventory",  # machine inventory
    "mstmachinemaster": "inventory",  # machine master data
    "mstmachineorg": "inventory",  # machine tariff info
    "mstmachineparameters1": "inventory",  # duplicate machine parameters
    "mstmedrack": "inventory",  # medication rack
    "mstmedtray": "inventory",  # medication tray
    "mstrolroqdeptmapping": "inventory",  # item to department mapping with reorder levels
    "mststoressubdepartment": "inventory",  # store subdepartment mapping
    "mstsuppliersregistration": "inventory",  # supplier registration
    "newtariff2019": "inventory",  # inventory tariff data
    "surendra": "inventory",  # inventory item details
    "tblinvcodes": "inventory",  # inventory codes and rates
    "tblpoinddtls": "inventory",  # purchase order details
    "tblpoindmst": "inventory",  # purchase order master
    "tblshipmentdtls": "inventory",  # shipment details
    "tblshipmentmst": "inventory",  # shipment master
    "trnbranchindentdet": "inventory",  # branch requisition details
    "trnbranchindentpri": "inventory",  # branch requisition primary
    "trnbranchissuedet": "inventory",  # item issue details
    "trnbranchissuepri": "inventory",  # item issue primary
    "trnbranchreturndet": "inventory",  # item return details
    "trnbranchreturnpri": "inventory",  # item return primary
    "trnconsumtiondetails": "inventory",  # item consumption
    "trndailyconsumptiondtls": "inventory",  # daily consumption
    "trnpofreeqtydetails": "inventory",  # purchase order free quantity details
    "trnpotermsconditions": "inventory",  # purchase order terms details
    "trnpurchase": "inventory",  # purchase transaction record
    "trnpurchasereturndetails": "inventory",  # purchase return line details
    "trnpurchasereturns": "inventory",  # purchase return header
    "trnpurcpaymnt": "inventory",  # purchase payment record
    "trnpurcpaymntmodeofcolctndetails": "inventory",  # purchase payment collection details
    "trnpurcretpaymntmodeofcolctndetails": "inventory",  # purchase return payment details
    "trnquotationfreeqtydetails": "inventory",  # quotation free quantity details
    "trnquotationtermsconditions": "inventory",  # quotation terms details
    "trnformdeptinvmapping": "inventory",  # inventory mapping (retry)
    "trnforminvdeduction": "inventory",  # inventory deduction (retry)
    "trngrnconcession": "inventory",  # GRN concession (retry)
    "trngrndetails26feb2020": "inventory",  # GRN details (retry)
    "trngrnfreeqtydetails": "inventory",  # free quantity details (retry)
    "trninventoryconsumption": "inventory",  # inventory consumption (retry)
    "trninventsupplierpaymts": "inventory",  # supplier payments (retry)
    "trnstock26feb2020": "inventory",  # stock details (retry)
    "trnstockinvconsumption": "inventory",  # stock consumption (retry)
    "trnstocktransfer": "inventory",  # stock transfer (retry)
    "trnstoresledger": "inventory",  # stores ledger (retry)
    "trnstoresmodeofcollectionsdet": "inventory",  # collection mode (retry)
    "trnparamresult": "labs",  # lab results
    "tbleqpresults": "labs",  # lab results
    "mstorginvestigationrates": "labs",  # lab investigation rates
    "trninvlabdet": "labs",  # lab test billing (retry)
    "trninvlabpri": "labs",  # lab priority info
    "trnstatustracking": "labs",  # sample status tracking
    "trndescresult": "labs",  # lab result description (retry)
    "trnsamplelogisacknow": "labs",  # sample logistics acknowledgement
    "trnsamplelogisdet": "labs",  # sample logistics details
    "mstinvpackages": "labs",  # test package catalog
    "trntempabnormalreport": "labs",  # lab abnormal report (retry)
    "mstparametertemplate": "labs",  # parameter templates
    "tblvitrosuploadeddata": "labs",  # lab test uploads
    "mstinvestigationsdtls": "labs",  # investigation details
    "mstinvestigationsdtls_pricelog": "labs",  # investigation price log
    "trntempautoauthentication": "labs",  # lab auto authentication (retry)
    "trnsamplelogispri": "labs",  # sample logistics primary
    "tbla15uploadeddata": "labs",  # uploaded lab test data
    "trnauthdeletiontrack": "labs",  # result entry deletion tracking
    "mstinvestigationsdtlslog": "labs",  # investigation details log
    "mstorginvestigationrateslogistics": "labs",  # lab rates logistics
    "mstlabdesctemp": "labs",  # lab test description temp
    "mstinvestigations": "labs",  # main investigations list
    "trnoutsrcsamplesdtls": "labs",  # outsourced samples
    "mstparametertemplatelog": "labs",  # parameter template logs
    "tblappcart": "labs",  # test cart details
    "trnoutsrcsamplespri": "labs",  # outsourced samples
    "mstparametercalculation": "labs",  # parameter calculation rules
    "mstinvestigationslog": "labs",  # investigation log
    "trninvlabdetloc16": "labs",  # lab bill detail record
    "mstinvestigationapi": "labs",  # investigation API mapping
    "trncomptemplabinvdetails": "labs",  # lab invoice details
    "mstparameterhead": "labs",  # parameter head definitions
    "trncomptempinvlabpri": "labs",  # lab invoice header
    "trnresultwithheld": "labs",  # withheld lab results
    "mstlabmachine": "labs",  # lab machine details
    "mstmethod": "labs",  # lab method definitions
    "trndifferentialcount": "labs",  # lab differential count (retry)
    "mstsampletype": "labs",  # sample type lookup
    "mstorganismtype": "labs",  # microbiology organism types
    "sampletypes": "labs",  # sample type definitions
    "mstinvestigationconcform": "labs",  # investigation form details
    "mstinvestigationmapping": "labs",  # investigation mapping
    "trnrclresponsepkgdtls": "labs",  # lab package response details
    "trnrclresponsestatus": "labs",  # lab response status
    "traymaster": "labs",  # tray for sample handling
    "trnappsampletracking": "labs",  # sample tracking
    "trninvlabprisweeja": "labs",  # lab priority record
    "mstbnprospec": "labs",  # lab test specifications
    "mstccinvpackages": "labs",  # grouping of lab tests
    "mstinvdisease": "labs",  # disease-test mapping
    "mstinvestigationsclubbed": "labs",  # clubbed investigations
    "mstinvestigationsdtls2019": "labs",  # investigation details 2019
    "mstinvestigationsdtlsexport": "labs",  # exported investigation details
    "mstinvestigationsexport": "labs",  # exported investigations
    "mstlabdesc": "labs",  # lab test description
    "mstlabdescshine": "labs",  # lab test description (shine)
    "mstlabmachine1": "labs",  # lab machine details (duplicate)
    "mstoltestparamsmapping": "labs",  # maps lab test parameters
    "mstorginvestigationrates1": "labs",  # lab investigation rates
    "mstorginvestigationrates2": "labs",  # lab investigation rates
    "mstorginvestigationrates3": "labs",  # lab investigation rates
    "radlabs": "labs",  # lab test rates
    "rajesh_pack": "labs",  # test package details
    "tbleqpresults1": "labs",  # lab results
    "trn_samplelogisacknow": "labs",  # sample logistics acknowledgement
    "trn_samplelogisdet": "labs",  # sample logistics details
    "trn_samplelogispri": "labs",  # sample logistics primary
    "trnbarcodenomodification": "labs",  # sample barcode changes
    "trncc_clubbed": "labs",  # clubbed lab requests
    "trncc_clubbedparamresult": "labs",  # clubbed param results
    "trncc_clubbedparamresults": "labs",  # clubbed param results mapping
    "trnlabreceipts": "labs",  # lab receipt records
    "trnlifeberries": "labs",  # lab bill detail record
    "trnlifeberriespri": "labs",  # lab priority info
    "trnolapilogdtls": "labs",  # lab sample log
    "trnolreportslogdtls": "labs",  # lab report log
    "trnolstatuslogdtls": "labs",  # lab status log
    "trnparamunitsloc1": "labs",  # parameter units for lab tests
    "trnpatientresultstemp": "labs",  # temporary patient test results
    "trncc_descresult": "labs",  # lab description result (retry)
    "trncc_invlabdet": "labs",  # lab test details (retry)
    "trncc_invstatus": "labs",  # lab status updates (retry)
    "trncc_paramresult": "labs",  # parameter results (retry)
    "trncc_samplelogisacknow": "labs",  # sample acknowledgement (retry)
    "trncc_samplelogisdet": "labs",  # sample logistics details (retry)
    "trncc_samplelogispri": "labs",  # sample logistics primary (retry)
    "trndescresult_audit1": "labs",  # audit description result (retry)
    "trndescresultfiles": "labs",  # result files (retry)
    "trnevolkolab": "labs",  # lab upload status (retry)
    "trnevolkoresults": "labs",  # lab result files (retry)
    "trntempinvlabpri": "labs",  # lab invoice patient data (retry)
    "trntempinvstatus": "labs",  # lab invoice status (retry)
    "trntemplabinvdetails": "labs",  # lab invoice details (retry)
    "mstpatientregistration": "patients",  # patient registration
    "trnpatdtlsmodificationlog": "patients",  # patient detail change log
    "tblappdeviceregistration": "patients",  # patient device registration
    "mstappaddress": "patients",  # patient address records
    "trntemppatientrepeatevisits": "patients",  # patient repeat visits (retry)
    "trntempinvpri": "patients",  # patient personal info (retry)
    "mstpatientgetdata": "patients",  # patient messaging data
    "mstmembershipsec": "patients",  # secondary membership info
    "mstmembershippri": "patients",  # primary membership info
    "trncomplaints": "patients",  # patient complaints (retry)
    "mstprooftype": "patients",  # document type reference
    "tblappnotification": "patients",  # patient notifications
    "mstpatientsourcegetdata": "patients",  # patient source info
    "mstproofofdocuments": "patients",  # patient document records
    "tbl_patientcalldata": "patients",  # patient call information
    "tbltempbulkposting": "patients",  # patient bulk posting
    "trnopconsultationdetails": "patients",  # consultation details
    "trncc_invlabpri": "patients",  # patient lab info (retry)
    "trncc_patdtlsmodificationlog": "patients",  # patient detail changes (retry)
    "trndeptpharmaindentdet": "pharmacy",  # pharmacy indent details
    "trndeptpharmaissuedet": "pharmacy",  # pharmacy issue details
    "trndeptpharmaissuepri": "pharmacy",  # pharmacy issue header
    "trndeptpharmaindentpri": "pharmacy",  # pharmacy indent header
    "trndeptpharmareturndet": "pharmacy",  # pharmacy return details
    "trndeptpharmareturnpri": "pharmacy",  # pharmacy return header
    "mstgeneric": "pharmacy",  # generic drug catalog
    "trndeptpharmaissuedet26feb2020": "pharmacy",  # pharmacy issue details
    "trndeptpharmareturndet26feb2020": "pharmacy",  # pharmacy return details
    "trnoutwards": "pharmacy",  # drug outwards
    "mstlocationusers": "staff",  # user to location mapping
    "mstroledtls": "staff",  # role details
    "mstlocauthorisation": "staff",  # location authorisation
    "mstappagentstatus": "staff",  # agent status tracking
    "mstroles": "staff",  # role definitions
    "mstempmapping_asm": "staff",  # user-employee mapping
    "tblagentappdeviceregistration": "staff",  # agent device registration
    "mstemptarget": "staff",  # employee target
    "mstappagentareamapping": "staff",  # agent area assignments
    "mstagentmaster": "staff",  # staff master
    "trndeptcomplaint": "staff",  # inter-department complaint
    "mstdesignation": "staff",  # staff role lookup
    "mstappagentleaves": "staff",  # agent leave records
    "mstreferencesource": "staff",  # source reference for staff
    "mstmaptechdoc": "staff",  # tech authorization mapping
    "tblappagentnotification": "staff",  # agent notifications
    "mstappbms": "staff",  # branch manager info
    "mstempmapping_gm": "staff",  # user-employee mapping
    "mstempmapping_rsm": "staff",  # user-employee mapping
    "mstrejectreason": "staff",  # rejection reason lookup
    "mstshifts": "staff",  # shift schedule
    "tbl_callusers": "staff",  # user account information
    "mstagentleaves": "staff",  # staff leave records
    "mstappagentassigndispatchorders": "staff",  # agent dispatch assignments
    "mstempadvances": "staff",  # employee advance
    "mstempexpenditure": "staff",  # employee expense
    "mstempleaves": "staff",  # employee leave
    "mstempplans": "staff",  # employee plan
    "mstempschedules": "staff",  # employee schedule
    "mstemptasks": "staff",  # employee task
    "mstrouteboy": "staff",  # personnel for sample transport
    "tblmobileappreg": "staff",  # user registration
    "trnrouteboymarkmapping": "staff",  # route boy mapping
    "trnccusermapping": "staff",  # user mapping (retry)
    "trncertificates": "staff",  # employee certificates (retry)
    "trnempmapping": "staff",  # employee mapping (retry)
}
