"""
Reviewed join hints used by describe_table.
Only include joins you trust. Wrong joins are worse than none.
"""

REAL_TABLE_RELATIONSHIPS = {
    # Patient core
    "mstpatientregistration": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],

    # Lab ↔ patient (confirmed)
    "trninvlabdet": [("PATID", "mstpatientregistration", "ID")],
    "trninvlabdetloc16": [("PATID", "mstpatientregistration", "ID")],
    "trninvlabpri": [("PATIENTID", "mstpatientregistration", "ID")],
    "trninvlabprisweeja": [("PATIENTID", "mstpatientregistration", "ID")],
    "trnlifeberries": [("PATID", "mstpatientregistration", "ID")],
    "trnlifeberriespri": [("PATIENTID", "mstpatientregistration", "ID")],
    "trntempinvstatus": [("PATIENTID", "mstpatientregistration", "ID")],

    # Collections ↔ patient (confirmed pattern)
    "trnmodeofcollectionsdet": [("PATIENTID", "mstpatientregistration", "ID")],
    "trnmodeofcollections": [("PATIENTID", "mstpatientregistration", "ID")],

    # Likely patient-linked billing (VERIFY column names with describe_table before relying)
    # Keep empty until you confirm column names — prevents bad joins.
    "trninvoicepayments": [("LOCATIONID", "mstlocationusers", "Id"), ("TRANSID", "trnstocktransfer", "ID")],
    "mstpaymentdetails": [("OrderId", "mstappagentassigndispatchorders", "ID")],
    "trninvpaydetails": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnmergeddocbilldtls": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnmergeddocbilldtls_referral": [("LOCATIONID", "mstlocationusers", "Id")],
    "daycollection_mobileapp": [("LOCATIONID", "mstlocationusers", "Id")],
    "trntempdaycollall": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trntempbranchwisecoll": [],

    # --- bulk-added from discover_table_relationships.py, filtered for confidence ---
    "cc_invoice": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "cc_invoicenew": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "konnectstock": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstagentmaster": [("LocationID", "mstlocationusers", "Id")],
    "mstantibiotics": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstappadditionalcharges": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstappagentleaves": [("LocationID", "mstlocationusers", "Id")],
    "mstappagentstatus": [("LocationID", "mstlocationusers", "Id")],
    "mstappbms": [("LocationID", "mstlocationusers", "Id")],
    "mstappbookingno": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstappbookingslots": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstappdiseaseinvdtls": [("DiseaseId", "mstinvdisease", "ID"), ("LOCATIONID", "mstlocationusers", "Id")],
    "mstccinvestigationrates": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstccinvpackages": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstccrefdoctor": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstconsumptionmaster": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstdesignation": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstdis_inv_insert": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "mstdocdeptinvdiscount": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstdoctor": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstdoctorslab": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstempmapping_asm": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "mstempmapping_gm": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "mstempmapping_rsm": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "mstempplans": [("PlanId", "mstmemplanswiseadditionalcharges", "ID")],
    "mstemptarget": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "mstgeneric": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "mstinvconsumables": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigationconcform": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigationmapping": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigations": [("LOCATIONID", "mstlocationusers", "Id"), ("OUTSOURCEID", "mstoutsourceinvmapping", "ID")],
    "mstinvestigationsclubbed": [("LOCATIONID", "mstlocationusers", "Id"), ("OUTSOURCEID", "mstoutsourceinvmapping", "ID")],
    "mstinvestigationsdtls": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigationsdtls2019": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigationsdtls_pricelog": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigationsdtlsexport": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigationsdtlslog": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvestigationsexport": [("LOCATIONID", "mstlocationusers", "Id"), ("OUTSOURCEID", "mstoutsourceinvmapping", "ID")],
    "mstinvestigationslog": [("LOCATIONID", "mstlocationusers", "Id"), ("OUTSOURCEID", "mstoutsourceinvmapping", "ID")],
    "mstinvinventorymap": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "mstinvoicesliptext": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvpackages": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvpackages2": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstinvpackageslog": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstitems": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "mstitemsr": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "mstitemtraymap": [("LocId", "mstlocationusers", "Id")],
    "mstitemtype": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "mstlabdesc": [("LocationId", "mstlocationusers", "Id")],
    "mstlabdescshine": [("LocationId", "mstlocationusers", "Id")],
    "mstlabdesctemp": [("LocationId", "mstlocationusers", "Id")],
    "mstlabmachine": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstlabmachine1": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstmachine": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstmachineinvmethodmap": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstmachinemaster": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "mstmachinemethodmap": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstmachineorg": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstmachineparameters": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstmachineparameters1": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstmanufacturers": [("UserID", "mstlocationusers", "Id")],
    "mstmapauthdoc": [("LocationID", "mstlocationusers", "Id"), ("SPECIALIZATIONID", "mstspecialization", "ID"), ("UserId", "mstlocationusers", "Id")],
    "mstmapsubauthdoc": [("LocationID", "mstlocationusers", "Id"), ("SPECIALIZATIONID", "mstspecialization", "ID"), ("UserId", "mstlocationusers", "Id")],
    "mstmaptechdoc": [("LocationID", "mstlocationusers", "Id")],
    "mstmedrack": [("UserID", "mstlocationusers", "Id")],
    "mstmedtray": [("UserID", "mstlocationusers", "Id")],
    "mstmemplanswiseadditionalcharges": [("LOCATIONID", "mstlocationusers", "Id"), ("ChargeID", "mstappadditionalcharges", "ID")],
    "mstmethod": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstoltestparamsmapping": [("HEADERID", "mstheaderpaytype", "ID"), ("LOCATIONID", "mstlocationusers", "Id")],
    "mstorganismtype": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstorgdeptdiscount": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstorginvestigationrates": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstorginvestigationrates1": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstorginvestigationrates2": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstorginvestigationrates3": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstorginvestigationrateslogistics": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstoutsourceinvmapping": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstparametercalculation": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstparameterhead": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstparametertemplate": [("HEADERID", "mstheaderpaytype", "ID"), ("LOCATIONID", "mstlocationusers", "Id")],
    "mstparametertemplatelog": [("HEADERID", "mstheaderpaytype", "ID"), ("LOCATIONID", "mstlocationusers", "Id")],
    "mstpatientgetdata": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstrack": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstrefdoctor": [("LOCATIONID", "mstlocationusers", "Id"), ("GROUPID", "mstreferralgroup", "ID")],
    "mstreferralgroup": [("GROUPID", "trnrefgroupinvmapping", "ID"), ("LOCATIONID", "mstlocationusers", "Id")],
    "mstrejectreason": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstrolroqdeptmapping": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstrouteboy": [("LOCATIONID", "mstlocationusers", "Id"), ("RouteBoyID", "trnrouteboymarkmapping", "ID")],
    "mstsampletype": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstschedule": [("LocationID", "mstlocationusers", "Id")],
    "mstshifts": [("LocationID", "mstlocationusers", "Id")],
    "mstspecialization": [("LOCATIONID", "mstlocationusers", "Id")],
    "mststoressubdepartment": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "mstsubitemtype": [("UserID", "mstlocationusers", "Id")],
    "mstsuppliers": [("UserID", "mstlocationusers", "Id")],
    "mstsuppliersregistration": [("UserID", "mstlocationusers", "Id")],
    "msttallyledgermaster": [("LocationID", "mstlocationusers", "Id")],
    "msttallyregledger": [("AutoId", "trntempautoauthentication", "ID"), ("LocationId", "mstlocationusers", "Id")],
    "msttempappinvdtls": [("OrderId", "mstappagentassigndispatchorders", "ID")],
    "msttempapppaymentdtls": [("OrderId", "mstappagentassigndispatchorders", "ID")],
    "msttemptallyregledger": [("AutoId", "trntempautoauthentication", "ID"), ("LocationId", "mstlocationusers", "Id")],
    "msttimings": [("LocationID", "mstlocationusers", "Id"), ("SlotId", "mstappbookingslots", "ID")],
    "msttray": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstunits": [("LOCATIONID", "mstlocationusers", "Id")],
    "mstuom": [("LOCATIONID", "mstlocationusers", "Id"), ("UOMID", "mstuommapping", "ID")],
    "mstuommapping": [("LOCATIONID", "mstlocationusers", "Id"), ("UOMID", "mstuom", "ID")],
    "mstworkstations": [("LocationID", "mstlocationusers", "Id")],
    "priceupdate": [("LOCATIONID", "mstlocationusers", "Id")],
    "priceupdatelog": [("LOCATIONID", "mstlocationusers", "Id"), ("PRICEUPDATEID", "priceupdate", "ID")],
    "rackmaster": [("LocId", "mstlocationusers", "Id")],
    "surendra": [("LOCATIONID", "mstlocationusers", "Id")],
    "tbl_callusers": [("UserId", "mstlocationusers", "Id")],
    "tblagentappdeviceregistration": [("deviceRegId", "tblappdeviceregistration", "id")],
    "tblappagentassignbill": [("areaId", "mstappagentareamapping", "id")],
    "tblappcart": [("locationid", "mstlocationusers", "Id")],
    "tblappdeviceregistration": [("deviceRegId", "tblagentappdeviceregistration", "id")],
    "tblcreditperiodgen": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "tblinvoicesms": [("LocationId", "mstlocationusers", "Id")],
    "tblmobileappreg": [("UserId", "mstlocationusers", "Id")],
    "tblshipmentmst": [("UserId", "mstlocationusers", "Id")],
    "tbltimings": [("SlotId", "mstappbookingslots", "ID")],
    "trn_samplelogisacknow": [("USERID", "mstlocationusers", "Id")],
    "trn_samplelogispri": [("USERID", "mstlocationusers", "Id")],
    "trnacntvoupaymntmodeofcolctndetails": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnappsampletracking": [("TrackingId", "trnstatustracking", "ID")],
    "trnbarcodenomodification": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnbillingcycleinvoicegeneration": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnbillingcyclerates": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnbranchindentdet": [("LocationID", "mstlocationusers", "Id")],
    "trnbranchindentpri": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnbranchissuepri": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnbranchreturnpri": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trncc_clubbed": [("USERID", "mstlocationusers", "Id")],
    "trncc_clubbedparamresult": [("LocationID", "mstlocationusers", "Id"), ("UserId", "mstlocationusers", "Id")],
    "trncc_clubbedparamresults": [("LocationID", "mstlocationusers", "Id")],
    "trncc_cshcrypayments": [("UserID", "mstlocationusers", "Id")],
    "trncc_cshcrypaymodedetails": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trncc_descresult": [("LOCATIONID", "mstlocationusers", "Id")],
    "trncc_paramresult": [("HEADERID", "mstheaderpaytype", "ID"), ("LOCATIONID", "mstlocationusers", "Id")],
    "trncc_samplelogisacknow": [("USERID", "mstlocationusers", "Id")],
    "trncc_samplelogispri": [("USERID", "mstlocationusers", "Id")],
    "trnccinvoicegeneration": [("UserID", "mstlocationusers", "Id")],
    "trnccpayments": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnccpayments1": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnccpaymodedetails": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnccusermapping": [("LOCATIONID", "mstlocationusers", "Id")],
    "trncertificates": [("LOCATIONID", "mstlocationusers", "Id")],
    "trncompmodificationlog": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trncomppayments": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trncomppaymentsrenova": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trncomppaymodedetails": [("LOCATIONID", "mstlocationusers", "Id"), ("TRANSID", "trnstocktransfer", "ID"), ("UserID", "mstlocationusers", "Id")],
    "trncomptempinvlabpri": [("LocationId", "mstlocationusers", "Id")],
    "trnconsignment": [("LocationId", "mstlocationusers", "Id")],
    "trnconsumtiondetails": [("LOCATIONID", "mstlocationusers", "Id")],
    "trndailyconsumptiondtls": [("LOCATIONID", "mstlocationusers", "Id"), ("WORKSTATIONID", "mstworkstations", "ID")],
    "trndelcreditbill": [("LOCATIONID", "mstlocationusers", "Id")],
    "trndeptcomplaint": [("Locationid", "mstlocationusers", "Id"), ("Userid", "mstlocationusers", "Id")],
    "trndeptconsumptiondet": [("LocationID", "mstlocationusers", "Id")],
    "trndeptconsumptionpri": [("LocationID", "mstlocationusers", "Id"), ("WorkStationID", "mstworkstations", "ID"), ("UserID", "mstlocationusers", "Id")],
    "trndeptpharmaindentdet": [("LocationID", "mstlocationusers", "Id")],
    "trndeptpharmaindentpri": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trndeptpharmaissuedet": [("LocationID", "mstlocationusers", "Id")],
    "trndeptpharmaissuedet26feb2020": [("LocationID", "mstlocationusers", "Id")],
    "trndeptpharmaissuepri": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trndeptpharmareturndet": [("LocationID", "mstlocationusers", "Id")],
    "trndeptpharmareturndet26feb2020": [("LocationID", "mstlocationusers", "Id")],
    "trndeptpharmareturnpri": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trndescresult": [("LOCATIONID", "mstlocationusers", "Id")],
    "trndescresult_audit1": [("LOCATIONID", "mstlocationusers", "Id")],
    "trndifferentialcount": [("LOCATIONID", "mstlocationusers", "Id")],
    "trndoctorweeklyoffs": [("LocationID", "mstlocationusers", "Id")],
    "trnempmapping": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trnevolkoresults": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnexecutivecashpayment": [("TransId", "trnstocktransfer", "ID")],
    "trnexecutivedenomination": [("TransId", "trnstocktransfer", "ID")],
    "trnformdeptinvmapping": [("LocationID", "mstlocationusers", "Id"), ("FormID", "mstinvestigationconcform", "ID")],
    "trnforminvdeduction": [("LOCATIONID", "mstlocationusers", "Id"), ("WorkStationID", "mstworkstations", "ID")],
    "trngrnconcession": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trngrnmaster": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trngrnreturns": [("LocationId", "mstlocationusers", "Id")],
    "trngrnreturnsdetails": [("GrnRetId", "trngrnreturns", "ID")],
    "trnhvadditionalcharges": [("LOCATIONID", "mstlocationusers", "Id")],
    "trninventoryconsumption": [("WorkStationID", "mstworkstations", "ID"), ("ConsumptionId", "mstconsumptionmaster", "ID"), ("LocId", "mstlocationusers", "Id")],
    "trninventsupplierpaymts": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trninvoicegeneration": [("UserID", "mstlocationusers", "Id")],
    "trninvoicetestlog": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnitemtrack": [("LocationId", "mstlocationusers", "Id")],
    "trnlabreceipts": [("USERID", "mstlocationusers", "Id")],
    "trnmergeddoctors": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnopeningstock": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnoutsrcsamplesdtls": [("LocationId", "mstlocationusers", "Id"), ("OutSourceId", "mstoutsourceinvmapping", "ID")],
    "trnoutsrcsamplespri": [("LOCATIONID", "mstlocationusers", "Id"), ("OutSourceId", "mstoutsourceinvmapping", "ID")],
    "trnoutwards": [("LocationID", "mstlocationusers", "Id")],
    "trnparamresult": [("HEADERID", "mstheaderpaytype", "ID"), ("LOCATIONID", "mstlocationusers", "Id"), ("OrganismTypeID", "mstorganismtype", "ID")],
    "trnparamunitsloc1": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnpatientresultstemp": [("AutoID", "trntempautoauthentication", "ID")],
    "trnpaymodechangelog": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnpurchase": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnpurchaseorder": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnpurchasereturns": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnpurcpaymnt": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnpurcpaymntmodeofcolctndetails": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnpurcretpaymntmodeofcolctndetails": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnquotation": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnreferalmgmtbilldtls": [("LocationId", "mstlocationusers", "Id")],
    "trnreferalmgmtbilldtls_del": [("LocationId", "mstlocationusers", "Id")],
    "trnreferalpartialpayments": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnreferalpartialpayments_del": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnreferalpayments": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trnreferalpayments_del": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trnrefgroupinvmapping": [("GROUPID", "mstreferralgroup", "ID"), ("LOCATIONID", "mstlocationusers", "Id")],
    "trnrejbillscancellationlog": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnresultwithheld": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnrouteboymarkmapping": [("LOCATIONID", "mstlocationusers", "Id"), ("RouteBoyID", "mstrouteboy", "ID"), ("USERID", "mstlocationusers", "Id")],
    "trnsamplelogisacknow": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trnsamplelogispri": [("USERID", "mstlocationusers", "Id")],
    "trnstatustracking": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trnstock": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnstock26feb2020": [("LocationID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trnstockinvconsumption": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnstocktransfer": [("LOCATIONID", "mstlocationusers", "Id")],
    "trnstoresmodeofcollectionsdet": [("LocationId", "mstlocationusers", "Id"), ("UserId", "mstlocationusers", "Id")],
    "trntariffupdate": [("LOCATIONID", "mstlocationusers", "Id")],
    "trntempabnormalreport": [("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trntempinvlabpri": [("LocationId", "mstlocationusers", "Id")],
    "trntempmoncoll": [("CASHPAID", "trnexecutivecashpayment", "ID"), ("LOCATIONID", "mstlocationusers", "Id"), ("USERID", "mstlocationusers", "Id")],
    "trntemppatientrepeatevisits": [("USERID", "mstlocationusers", "Id")],
    "trntemprejbills": [("LOCATIONID", "mstlocationusers", "Id")],
    "trntrackcreditamts": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
    "trntrackcreditamts_new": [("LOCATIONID", "mstlocationusers", "Id"), ("UserID", "mstlocationusers", "Id")],
}


def get_relationships_for_table(table_name: str) -> list:
    """Returns [(column, joins_to_table, joins_to_column), ...] or []."""
    return REAL_TABLE_RELATIONSHIPS.get(table_name.strip().lower(), [])